# -*- coding: utf-8 -*-
"""DataScience Classwork2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RxJdQvndDwGRZRXk9u9wORQS6946uf5K

Question 1
"""

import pandas as pd
import numpy as np

# employee details
emp = {
    "emp_id": [101,102,103,104,105],
    "name": ["Arun","Meena","John","Sara","Kiran"],
    "designation": ["Manager",np.nan,"Developer","Analyst",np.nan],
    "yrs_of_experience": [5,2,7,3,4],
    "age": [30,25,35,28,32],
    "salary": [15000,8000,12000,9000,11000]
}

df = pd.DataFrame(emp)

print("Original data")
print(df)

df = df[df["salary"] <= 10000]

print("\nAfter removing high salary employees")
print(df)

df["designation"] = df["designation"].fillna("Not Specified")

print("\nAfter filling missing designation")
print(df)

df["age"] = df["age"] + 3

df.rename(columns={"yrs_of_experience":"experience"}, inplace=True)

print("\nFinal dataframe")
print(df)

"""Question 2 Join and Concat


"""

import pandas as pd

students_data = {
    "student_id": [1, 2, 3, 4],
    "name": ["Arjun", "Priya", "Rahul", "Sneha"],
    "age": [20, 21, 19, 22],
    "department": ["CSE", "ECE", "IT", "CSE"]
}

students_df = pd.DataFrame(students_data)

marks_data = {
    "student_id": [1, 2, 3, 5],
    "maths": [85, 78, 92, 70],
    "physics": [80, 74, 89, 65],
    "specialization": ["AI", "Embedded", "Data Science", "Cyber"]
}

marks_df = pd.DataFrame(marks_data)

inner_merge = pd.merge(students_df, marks_df, on="student_id", how="inner")
print("INNER JOIN:")
print(inner_merge)

outer_merge = pd.merge(students_df, marks_df, on="student_id", how="outer")
print("\nOUTER JOIN:")
print(outer_merge)


left_merge = pd.merge(students_df, marks_df, on="student_id", how="left")
print("\nLEFT JOIN:")
print(left_merge)

right_merge = pd.merge(students_df, marks_df, on="student_id", how="right")
print("\nRIGHT JOIN:")
print(right_merge)

concat_vertical = pd.concat([students_df, marks_df], axis=0)
print("\nCONCAT (Vertical):")
print(concat_vertical)


concat_horizontal = pd.concat([students_df, marks_df], axis=1)
print("\nCONCAT (Horizontal):")
print(concat_horizontal)

"""Drop rows where salary > 10000

"""

df = df[df["salary"] <= 10000]

print("\nAfter dropping salary > 10000:")
print(df)

"""Handle NaN in designation"""

df["designation"].fillna("Not Specified", inplace=True)

print("\nAfter handling NaN in designation:")
print(df)

"""Increment age by 3"""

df["age"] = df["age"] + 3

"""Rename yrs_of_experience → experience"""

df.rename(columns={"yrs_of_experience": "experience"}, inplace=True)

print("\nFinal Cleaned DataFrame:")
print(df)

"""Question 3 Create Sales Data"""

import pandas as pd

sales_data = {
    "Month": ["Jan", "Feb", "Mar"],
    "Product_A": [10000, 12000, 9000],
    "Product_B": [15000, 13000, 11000],
    "Product_C": [8000, 9500, 7000]
}

sales_df = pd.DataFrame(sales_data)

print("Original Sales Data (Wide Format):")
print(sales_df)

"""Use melt() (Wide ➝ Long)"""

melted_df = pd.melt(
    sales_df,
    id_vars=["Month"],
    var_name="Product",
    value_name="Sales"
)

print("\nMelted Data (Long Format):")
print(melted_df)

"""Use pivot() (Long ➝ Wide)"""

pivot_df = melted_df.pivot(
    index="Month",
    columns="Product",
    values="Sales"
)

print("\nPivoted Data (Back to Wide Format):")
print(pivot_df)