# -*- coding: utf-8 -*-
"""DataCleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KUrMiM8SUruG30nHqKZUcs_ckbtAtbLH
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np

from sklearn.impute import KNNImputer
from sklearn.linear_model import LinearRegression
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer


df = pd.read_excel("Copy of House Price.xlsx")

print("NA values in original dataset:")
print(df.isna().sum())


df_simple = df.copy()

numeric_cols = df_simple.select_dtypes(include='number').columns
categorical_cols = df_simple.select_dtypes(include='object').columns

for col in numeric_cols:
    df_simple[col] = df_simple[col].fillna(df_simple[col].mean())


for col in categorical_cols:
    df_simple[col] = df_simple[col].fillna(df_simple[col].mode()[0])

print("\nNA after Mean/Mode Imputation:")
print(df_simple.isna().sum())


df_knn = df.copy()

numeric_data = df_knn.select_dtypes(include='number')

knn = KNNImputer(n_neighbors=3)
df_knn[numeric_data.columns] = knn.fit_transform(numeric_data)

print("\nNA after KNN Imputation:")
print(df_knn.isna().sum())


df_reg = df.copy()

numeric_cols = df_reg.select_dtypes(include='number').columns

for col in numeric_cols:

    temp = df_reg[numeric_cols].copy()

    train = temp[temp[col].notna()]
    test = temp[temp[col].isna()]

    if len(test) > 0:

        X_train = train.drop(col, axis=1)
        y_train = train[col]

        X_test = test.drop(col, axis=1)

        X_train = X_train.fillna(X_train.mean())
        X_test = X_test.fillna(X_test.mean())

        model = LinearRegression()
        model.fit(X_train, y_train)

        df_reg.loc[df_reg[col].isna(), col] = model.predict(X_test)

print("\nNA after Regression Imputation:")
print(df_reg.isna().sum())



df_multi = df.copy()

numeric_cols = df_multi.select_dtypes(include='number').columns

imputer = IterativeImputer(max_iter=10, random_state=0)

df_multi[numeric_cols] = imputer.fit_transform(df_multi[numeric_cols])

print("\nNA after Multiple Imputation:")
print(df_multi.isna().sum())

from google.colab import files
uploaded = files.upload()

import pandas as pd
import numpy as np
from sklearn.impute import KNNImputer
from sklearn.linear_model import LinearRegression
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

df = pd.read_excel("Titanic.xlsx")

print("NA values in original dataset:")
print(df.isna().sum())

df_simple = df.copy()

numeric_cols = df_simple.select_dtypes(include='number').columns
categorical_cols = df_simple.select_dtypes(include='object').columns

for col in numeric_cols:
    df_simple[col] = df_simple[col].fillna(df_simple[col].mean())

for col in categorical_cols:
    df_simple[col] = df_simple[col].fillna(df_simple[col].mode()[0])

print("\nNA after Mean/Mode Imputation:")
print(df_simple.isna().sum())

df_knn = df.copy()

numeric_data = df_knn.select_dtypes(include='number')

knn = KNNImputer(n_neighbors=3)
df_knn[numeric_data.columns] = knn.fit_transform(numeric_data)

print("\nNA after KNN Imputation:")
print(df_knn.isna().sum())

df_reg = df.copy()

numeric_cols = df_reg.select_dtypes(include='number').columns

for col in numeric_cols:

    temp = df_reg[numeric_cols].copy()

    train = temp[temp[col].notna()]
    test = temp[temp[col].isna()]

    if len(test) > 0:

        X_train = train.drop(col, axis=1)
        y_train = train[col]

        X_test = test.drop(col, axis=1)

        X_train = X_train.fillna(X_train.mean())
        X_test = X_test.fillna(X_test.mean())

        model = LinearRegression()
        model.fit(X_train, y_train)

        df_reg.loc[df_reg[col].isna(), col] = model.predict(X_test)

print("\nNA after Regression Imputation:")
print(df_reg.isna().sum())

df_multi = df.copy()

numeric_cols = df_multi.select_dtypes(include='number').columns

imp = IterativeImputer(max_iter=10, random_state=0)

df_multi[numeric_cols] = imp.fit_transform(df_multi[numeric_cols])

print("\nNA after Multiple Imputation:")
print(df_multi.isna().sum())